const graphql = require("graphql");

/**
 * The schema generated by Umbraco isn't interpreted correctly by WebStorm, because the arguments order changes between interface and implementation on some fields.
 * Ensure all arguments are sorted the same way to avoid this.
 * @param schema
 * @return {*}
 */
function sortSchemaArgs(schema) {
  schema.__schema.types.forEach((type) => {
    type.fields?.forEach((field) => {
      field.args?.sort((a, b) => {
        if (a.name < b.name) {
          return -1;
        }
        if (a.name > b.name) {
          return 1;
        }
        return 0;
      });
    });
  });

  return schema;
}

module.exports = {
  plugin: (schema, _documents, pluginConfig) => {
    const introspection = graphql.introspectionFromSchema(schema, {
      descriptions: true,
      directiveIsRepeatable: true,
    });

    return JSON.stringify(sortSchemaArgs(introspection), null, 2);
  },
};
